title: Vilkårlig Trekant Python Program
description: Dette er et program der løser en vilkårlig trekant med kun tre kendte værdier.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
<meta name="google-site-verification" content="C2FHn1WicQv9iLTDGAYaceEX9f4XljnFAWn4mZa6jb8" />
